apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [{
         "apiVersion": "insightedge.example.com/v1alpha1",
         "kind": "Edge",
         "metadata": {
            "name": "example-insightedge"
         },
         "spec": {
            "image": {
               "registry": "registry.access.redhat.com",
               "repository": "gigaspaces/insightedge-enterprise-14-0",
               "tag": "latest",
               "pullPolicy": "IfNotPresent"
            },
            "service": {
               "type": "ClusterIP",
               "port": 3306
            },
            "serviceAccountName": "insightedge-operator",
            "resources": {}
         }
      }]
    categories: "Monitoring,OpenShift Optional"
    capabilities: "Basic Install"
    certified: "true"
    containerImage: docker.io/yoramw/insightedge-enterprise-operator:v0.0.1
    createdAt: 2019-04-25T12:59:59Z
    description: Deploy the InsightEdge agent from a helm chart onto your Kubernetes or OpenShift cluster
    repository: https://github.com/RHC4TP/operators/tree/master/partners/gigaspaces-insightedge-operator
    support: Red Hat Connect
  name: insightedge-operator.v0.0.1
  namespace: "placeholder"
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: InsightEdge is an in-memory real-time analytics platform for instant insights to action. It's an always-on platform for mission-critical applications across cloud, on-premise or hybrid. InsightEdge operationalizes machine learning and transactional processing, at scale; analyzing data as it's born, enriching it with historical context, for instant insights.
        displayName: InsightEdge Operator
        kind: Edge
        name: edges.insightedge.example.com
        resources:
          - kind: Deployment
            name: ""
            version: apps/v1
          - kind: Pod
            name: ""
            version: v1
          - kind: Service
            name: ""
            version: v1
          - kind: Secret
            name: ""
            version: v1
          - kind: ConfigMap
            name: ""
            version: v1
        specDescriptors:
          - description: The registry base URL fo InsightEdge
            displayName: Registry URL
            path: image.repository
          - description: Registry namespace/repository for InsightEdge
            displayName: Image Repository
            path: image.repository
          - description: Container image tag for InsightEdge
            displayName: Image Tag
            path: image.tag
          - description: Image pull policy stating whether or not to pull from the local image store
            displayName: Pull Policy
            path: image.pullPolicy
          - description:  Service type to create
            displayName: Service Type
            path: service.type
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:core:v1:Service'
          - description:  Service port to expose internally
            displayName: Service Port
            path: service.port
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:core:v1:Service'
          - description: Service account name used to deploy InsightEdge
            displayName: Service Account Name
            path: serviceAccountName
          - description: Define resources requests and limits for individual Pods
            displayName: Resource Requirements
            path: resources
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:resourceRequirements'
        statusDescriptors:
          - description: Current deployed state
            displayName: Conditions
            path: conditions
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.conditions'
        version: v1alpha1
  description: |
    This is an Operator for InsightEdge, developed using the InsightEdge helm chart available at (https://github.com/RHC4TP/operators/blob/master/partners/gigaspaces-insightedge-operator/helm-charts/edge)
    
    The operator will deploy the InsightEdge agent (using the helm chart) on your Kubernetes or OpenShift cluster as a Daemonset.

    ## Prerequisites
    The InsightEdge Operator will (by default) deploy the latest version of InsightEdge Infrastructure from Red Hat Software Collections for RHEL 7.
    The image will pull from the [Red Hat Container Catalog](https://access.redhat.com/containers), which will require the following:

    * RHN account (https://access.redhat.com)
    * RHCC Image pull secret in your project/namespace or [Red Hat Container Registry Authentication](https://access.redhat.com/RegistryAuthentication) setup on your OpenShift cluster

    To create an `rhcc` secret using docker (requires root/sudo or you must be in the docker group):
    ```
    # docker login -u <username> registry.connect.redhat.com
    Password:
    Login Succeeded
    # oc create secret generic rhcc --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson
    ```

    To create an `rhcc` secret using podman:
    ```
    $ podman login -u <username> registry.connect.redhat.com
    Password:
    Login Succeeded!
    $ oc create secret generic rhcc --from-file=.dockerconfigjson=$XDG_RUNTIME_DIR/containers/auth.json --type=kubernetes.io/dockerconfigjson
    ```

    To link the `rhcc` secret to the `default` service account to use as an image pull secret in the current project/namespace:
    ```
    $ oc secrets link default rhcc --for=pull
    ```

    ## Required Parameters
    There is only one required parameter, and that is the Agent Key available by logging into [InsightEdge](https://infrastructure.insightedge.com).
  
    Note that the Agent Key is kept in a base64-encoded K8s Secret, however the key is also visible as plain text within the Custom Resource spec.
      
    Values listed below are relative to the `spec:` field in the Custom Resource.
     
    * **insightedge.agent.key** - Your InsightEdge Agent Key

    ## Advanced Features

    This is mostly a TODO section, however you can define your own values as required for the following fields:

    Values are relative to the `spec:` field in the Custom Resource.

    * **image.registry** - The dns hostname of the desired container image registry (defaults to `registry.access.redhat.com`)
    * **image.repository** - The repository path (appended to the registry URL) above where the container image resides (defaults to `rhscl/insightedge-102-rhel`)
    * **image.tag** - The container image tag (defaults to `:latest`)
    * **db.config** - The InsightEdge configuration populating `my.cnf` inside the container. Keep in mind that the `rhscl/insightedge-102-rhel` container is hard-coded to expose port 3306 (if you want to change this then you'll have to specify a custom MariaDB container image)
    * **resources** - Define your own Pod resource limits (`limits.cpu` and `limits.memory`)
    * **service.type** - The type of Service to configure for InsightEdge (defaults to `ClusterIP`)
    * **service.port** - The TCP port that the Service will listen on    
    * **serviceAccountName** - The name of the service account used to deploy InsightEdge (NOTE: This **must** match what is defined in the ClusterServiceVersion)
  displayName: InsightEdge Operator
  version: 14.0.1
  maintainers:
    - name: GigaSpaces Technologies Ltd.
      email: support@gigaspaces.com
  links:
    - name: Blog
      url: https://www.gigaspaces.com/blog/
    - name: Documentation
      url: https://docs.gigaspaces.com/
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAANUAAAD4CAYAAAB7cqNrAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAADP9JREFUeNrsnf2PHGUdwJ/Z8HvXl2hijFmq4gs0bImIISC7pQ2WSrgzREMI3p7SGKNClxCCGriW+IIhelsgJuYkt0VDNERuq1CRFm4rEkx96QKigWC7xhij8WX4A9zx+8zO9ubau1539pmdZ579fJrnZu9mZ3rzPM9nv88z9zzPKAUAAGAzHlngPruX3yjLpqhfL1Q3tckRpIIE3HLkvzXleTNSwJXT9wVKdWRzUAVB4/vb3+STW0gFZ+Gzh/+jo9KSCFXa8M1BoIWqP7zjzU1yDqlgDWZ/8e8pzxOhhiQI1OziNW9BLKSCOLWf/0tHpuODvlMCpps739oiJ0enQBa4QS/ozQVBUJSkkiQ5fp5cJFJBxM0/+0dJSvLkyCcK1PQPrns70YpIBb1eUAl6EnFGTHKeq8jN0TmPLMg/Qa9XCsycqkxuIhVoqYKATEAqMNz8IxOQCgw3/8gEpAIiFVIBfSpAqkmKVDT/kAoMhyqyAKmASIVUYLdUhCqkArOtPyIVUgGRCqnA7kjFLXWkAiIVUgF9KkAqmn+AVDBCpEIqpAL6VEgFNP8AqWj+AVIBkQqpwJo+FbfUkQqIVEgFdkcqpEIqQCqkyo5fvbK9ovrPWIqvnnpUUuuKC490KEK9jjpSmWb38hsl2UxF9W7w0Add344uVDe1cilVJNOipNIau/W+OXlPW7azIld3ovtU3KgwKZMWaE7SnnXq3R55j65v+0Su5lrnKFgqlH4CxfI6Qp1+kcfl/RO9XPH/JFKZSggV1rs9G7xV18tFef9SdIzdUokgi+dwUXHCjJhksUw8nGCQEGqo9eSnomPslUrEqMmmluDQiRYr6TOp1koINTRlOX7eSqlECH1hozx4bGLFIlJlJtQA3c+q2Bipair5ozUnWiwiVaZCDZixUaoZQ+eZOLGQKnOhVLzbYpNUJiWYKLFo/mUu1OC8FetuVBhmcsTSEcZUQqiRcf2ZvxMhVi98uryZhFBuSeUjVtLmX89YQqiR6NomVYuIlTRSqa7uDhlIHYRKLtRCdZN1Uh2gKZg4UrUNRaqjCJWYfYMXnk0ZEI3525Pyf6ObmVXXRri/5/anllR/2EziT9rXv/Ox8xEqER2JUlttvVGhbU+7srsZsYKgHvQCf4Tb6XWESvwhPW3rjQol0SOMIog1PK/P7+wGWqxkf/Rt/Lmxs4VQyVo9g76Ulc2/WDNwrJniUlNw862HKiLJevPQzrh+z/PqJx64tolQiYU6o+54tmYOYiWn9KUndd7VvCCYWSf/usrzDgRKNboP7vIRypxQVkuFWOY4/4tPVOKd6pMPfdx37RptEcp6qRAL8iZULqRCLMiTULmRCrEgL0LlSirEgjwIlTupEAtsFyqXUiEWQtksVG6lQiyEslWoXEuFWAhlo1CaXM/8HfNYwUWqdqbM50Go3Es1ZrHK0WKfMP4opWWq5UEoJ6Qas1gzVPFMmMmLUM5INUaxKtTvTCjnRSinpBpzxAI3pDIulHNSIRZkLZSTUiGWk3TyIpSzUqUoVov6nXupUhXKaalSEusg9TsT9udFKOelMixWR87VpH6Pn2hhlWYehJoIqQyJpY+fpXpnil5CrWu7UBMjlQGx6oz7yzxaDdbX820WaqKkOk2s1jAFQrPPGrG0GFuH+GDsjFsojTepBRSN45tTa6+P50ed40YkIljG7uU3Niw/kWlvFr+bN+mFE61SW44Kx49uSLSptrmR64zyE5koPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC9jwQdrH1H0ltfYTwLOk+2F1V5fig9xIFYk0J2lKUtHS310/ibwlaR+CgdVSiVA12cxbLNNactVFrCbFCdZJFQm1mNNrmUUssEoqEaosm+M5v56qiNWmWCFLCrHX8w5czxxFClZEqujGxElHrmmrRKsORQtZR6oph65pimIFG6S62KFruphiBRukKjl0TUWKFWyQCgAMS9V16Jq6FCvYINWLDl3TixQr2CBVy6FralGskLlU0YBUFypjm8G1YEuk0tRVf3BqXtG/+yxFCtZIFX3C13N8LXWiFNjAWlM/KrJZUvma+qFHqNOXAjulisTSQtUkXS+pYmv/SdJBSU0RyqcoAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBpvEm++AvueLqogqASBKocBD15qSQFXdnVOrH/Wp54bzmv3bOlKJuKpHLsx2H5XXDvyz5SjZkP3Hl4by9Qt4lExaBvkxZqIJZ8UU35su/EA7u6VF8rZdoj6TZJxXXeJuWn6lnINXFSXfjlZ0QitSzilOMSrSOWL9v6yQd3NanK1gilo9LyWWSKo4WqilgdpEqJi766rJt7kVArMm0glt7OIlbuhMpMrImRasvdR08JpdaQ6RzEqopYbap2ZkKVZHN8SKEyEaswCQVSvueXxYInn3CeV/Y8+RyR5IVJRdvVr0/fr/rbRap2piwmFEpFxy1HkQ6pRmXr3ueKquBJk8ErF3RcXkeccxCrtPnWQzXqdmbNvsqIpxmbWE5Ldcm9zxdFiGVRouz1jVIjijVDFc8EU/k+FrGclerSr78gTT7vVJMvdGl0sSrU72xa8AbPlbpYTkp12Td/3Y9QBd3ki4lhQCzIvVSpi+WcVJd/61gYoUSAfoQqaIHMiQXOkJpYTkl15f2/iYTqR6hTUhgUCzKhkyexnJHqo9/+XVHFI5TXF8mwWC3qt1NSpSKWE1JVGsf7fSiJUMrrS5KSWAep35mwP09NwdxLVd3fKUp9D29KxJtpKYjVfvX+HU3q9/i54N6Xu7Jp5EWsXEu1/aGXwggV3jaP5EhJLF+201TvTMWqp9wMNCZWbqXa8d0/hH2oQiE29CgdsXxJ1T/edzXzqyxomORBrFxKdc33XpEIpVb6UIVYZDErli/7q698Y1uH+mxFtPLzIFbupNq58CfpQ3lRH0qtiGNeLBFKVV/6WgWhEGsocvWHl10Pv6pn6fbnQ/UCFf7rxadoBKrXi03fkGOCXrBqSkcvNsWjF5/y0et/H0378OVVtbP3SoSylGj2r55blfYA2aGnjeRGqusWX4uEUuVTc6DSEcuXb6q/n7sCoRArkVi5kOr6R17vC9U7cwq8YbF8eV/1t3dfjlCIlVgs66Wa+uGJ2BT4ICaHcbF82VSPfeUjCIVYI4lltVSfePRkGKFUvMmXjlh6gZfqC3dd5qRQh488W4463mrH9m1txEpXLGuluuFHf1m5KbGyTkQaYvnybfX5Oy/tOCZSTfUn91XW2K2vVQ+5aohkPmKZFctKqT712F+LvVV9qEClJFYYoZ6740Mdh2TSFWpJUukcK0ddxGoiljmxrJPqxsf/VhQBpMkXlHurxDEuVnhT4ujtl7gk1FQk1LDMIpY5sayS6qaDfy9KRQ+bfL3eoM+TiljhbfPlPVtdEkpHpqRLeGmmRawWYo0ullUjKjzPW/KiNSUKhcFICG/V6IjYkmErqbDGVA39MzXYt2rkhR4c65RQEXMjCKWZdykzxjzyYimS2C6pPv3kPyt6YZW4QCmIFQ6OffbWi127KaGjVG3E05Si5iNiJcg71V/b3S6ppMLfdkqMdMSSCKWqR76wxcXb5hVD57nKtYwZo1gzNkpVWSWGWbF8+Vp9+vMXufqH3ZKh85RdzJwxiVUaDL61R6qCVzxDDDNihX2opz73QUZKTDBjEqtoW6RaLYsZscIm36Fb3o9QMLamoE2RyrRYvuyvPvGZ9yEUjEss3y6plGobFCts8v105r0IBeMSyx/8rcqmSHXAMxOxfBGr2rr53QgF4xSrZV3zb2FbsSlydEcUK4xQSzdtRigYt1j7rJMqulsx2/+7UiKxwj7UT24sIRSMW6x90dqE9km1UN3UTihWOFLisU++C6Fg3GI15fi98R9Yt5qSiNUcUqyObvL9+IZ3IhSYEKs9xGENOW729B9auURZJNb5Ik1rA7Eausn36PQ7EAqMiCVJi6VXwz3b5E0tXjVaNfcMzrP1AkUs3Uad3v2MX1JBMCVhqz8KOJys4ul9rUeuexurxkIacul12xuv3bNFDzCOD93S9a290RoV59l+gQtXF7VADYoaMpBL3yYfeo5ZgawDMAtSASAVAFIBIBUAIBUAUgEgFQAgFQBSASAVACAVAFIBIBUAUgEAUgEgFQBSAQBSASAVAFIBAFIBIBUAUgEAUjlH19B5WD4bqSCibeg8R8lKpAJhx/ZtOlK1RjxNV87TIjeRClbY6EkV53I8IBWcFq2SitEgSpnDIwvc4vCRZyuyWZRUOoe368hWF6Ga5BxSwdnF0s/yqkmaUaufr3Sq/yTpQBSheMYXUkHC6DWgg0gAAACTzP8FGABPtda5vlEUzgAAAABJRU5ErkJggg==
      mediatype: image/png
  install:
    spec:
      deployments:
        - name: insightedge-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: insightedge-operator
            template:
              metadata:
                labels:
                  name: insightedge-operator
              spec:
                serviceAccountName: insightedge-operator
                containers:
                  - name: insightedge-operator
                    # Replace this with the built image name
                    image: docker.io/yoramw/insightedge-enterprise-operator:v0.0.1
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: "insightedge-operator"            
      permissions:
        - serviceAccountName: insightedge-operator
          rules:
          - apiGroups:
            - ""
            resources:
            - pods
            - services
            - endpoints
            - persistentvolumeclaims
            - events
            - configmaps
            - secrets
            verbs:
            - '*'
          - apiGroups:
            - ""
            resources:
            - namespaces
            verbs:
            - get
          - apiGroups:
            - apps
            resources:
            - deployments
            - daemonsets
            - replicasets
            - statefulsets
            verbs:
            - '*'
          - apiGroups:
            - monitoring.coreos.com
            resources:
            - servicemonitors
            verbs:
            - get
            - create
          - apiGroups:
            - insightedge.example.com
            resources:
            - '*'
            verbs:
            - '*'
      # Required to run on OpenShift
      #clusterPermissions:
      #  - rules:
      #      - verbs:
      #          - use
      #        apiGroups:
      #          - security.openshift.io
      #        resources:
      #          - securitycontextconstraints
      #        resourceNames:
      #          - anyuid
      #    serviceAccountName: insightedge-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - database
    - sql
    - Real-time analytics
    - Real-time ML, 
    - In-memory Computing 
    - In-memory Computing platform 
    - High performance computing
    - Big Data analytics 
    - Accelerate data lakes
    - Kubernetes
    - Microservices
    - event-driven analytics
  maturity: alpha
  provider:
    name: GigaSpaces
